:doctype: book
:toc:
:toclevels: 3


= Economics Aspects of Blockchains



The goal of this section is to discuss in which ways the economic concepts previously described play a role in Blockchains.
We will discuss the market but also the resources that are traded on it, like block space and state storage.
We will se examples of opportunity costs in these markets and the consequences of the network effects in blockchain.

Remind what a market is: a market is a system where individuals, institutions, or even automated protocols engage in value exchange.
A Blockchain has a unique market of its own. They often behave differently from traditional markets.
But the same economical principles apply.


== Blockspace

Blockchains have many valuable resources to offer, the most obvious being cryptocurrencies. Block space is another important resource of Blockchains.
For instance, in bitcoin transactions are packed into blocks, if we want our transaction to be packed into a block we need to pay a fee for the space it occoupies on a block.
In the bitcoin market, users bid for block space by attaching fees to their transactions. The next block producer fills the block to the capacity with transactions offering the highest bid.
It is an auction-like market where the higher is the demand, the higher winning bids.
One interesting point about this market is how volotile it can be.
If you look at the average bitcoin transaction fee over time, you see big spikes where fees triple in value only to drop down again after a few months.
It is much more volotile than traditional markets. Why we see that in Blockchains ?
It is all about supply and demand. To be more precise is about the elasticity of supply.
In most markets when demand increases, suppliers respond by making more of the product. (e.g., the demand of ice cream increases, the supplier adjust the supply, if the adjustment is quick we call that highly elastic).
In bitcoin, adding more miners does not change the supply of block space at all. Block will continue to be create every 10 minutes on average.
Hence, the supply is completely inelastic, and any seasonal change in the demand is fully reflected in the price.
It is important to note that, alghtough increasing the miners does not increase the block space, it does improve the network security.

Many recent technologies in blockchains like roll-ups and parachains, answer the question of how to scale up the block space without affecting the security.
The goal is to make the block space more elastic, so it can better match the demand.


== Blockchain state

Another scarce resource in Blockchain networks is state storage.
Lets take ethereum as an example.
Ethereum is run on computers called validators, equivalent to bitcoin miners.
Ethereum allows developers to deploy applications called smart contracts, which makes the network much more versatile.
Unlike transactions that occoupies a single block the data generated by smart contracts need to be stored permanently by all validators.
The aggregate of all this application data constitutes the ethereum state, and is currently hundreds of gigabytes in size and growing.
Much of this state data is data that no one uses anymore. This is know as state bloat problem.

One solution for this is state rent. The idea is, users pay by the space that their contract occupies.
If they stop paying their date gets evicted.
This encourages developers to be mindful about the space they use.

Ethereum does something slighly different, developers provide a deposit in Ether when deploy a contract, and receive a refund when they clean up data they no longer need.
Speaking of incentives it brings us to opportunity costs.

=== Opportunuty costs

Opportunity cost refers to the potential benefits you miss out on when you choose one option over another.
For instance, regaring state rent:  users pay a fee to keep their data stored on the Ethereum blockchain,
to prevent unlimited growth of the blockchain’s state (which can slow down the network and increase storage costs for node operators).
If you keep your data on-chain and pay rent, your opportunity cost is the alternative use of that ETH (like staking, trading, or investing elsewhere).
If you choose not to pay state rent (delete data or move off-chain), your opportunity cost might be losing permanent on-chain access or functionality.
In other terms: You trade off the benefit of storing your data forever for the potential to use your ETH elsewhere.

Other examples:
- If you stake your ETH to earn staking rewards, your opportunity cost is that you can’t use that ETH to trade, invest elsewhere, or sell if the price spikes.
- If you hold ETH instead of staking, your opportunity cost is the staking rewards you could have earned.



== Network effects

A metwork effect happens when the value that a user derives from a service depends on the number of other users of that service.
We see that in telephone networks, social media apps, financial exchange, and also in blockchains.
Private companies can use network effects to gain a competitive advantage.
This is the reason for instance, that is difficult to create a new social network app, you can add better functionalities than the main networks,
but people wont use them if they dont have other people to interact with.

The case of blockchains like Ethereum and Polkadot is different, because they are public infra-structures, so the network effects benefit everyone.
Unlike a traditional network in web2, where every application in it belongs to a single company, can be created by anyone.
So, users, developers and validators take advantage of the network effect, which creates more interactions and business opportunities and increases the token value.

 
//TODO: add the economics of polkadot here ?


== References:


- https://www.rob.tech/blog/polkadot-blockspace-over-blockchains/

- https://polkadot-blockchain-academy.github.io/pba-content/singapore-2024/syllabus/2-Economics/4-Economics_of_Polkadot-slides.html#/21/0/2

- https://online.hbs.edu/blog/post/what-are-network-effects
